@extends('layout')
@section('title', 'Quienes somos')
@section('content')
@extends('generico')
@section('titulo', 'QUIENES SOMOS')
@section('contenido', 'Whereby is the super simple way to connect over video. No downloads or long having into meeting links.')
@include('quienes.mision')
@include('quienes.valores')
@include('quienes.comision')
@include('include.cta')
@include('include.footer') 
@endsection