@extends('master')
@section('titulo', 'Noticias | CKFM')
@section('contenido')
@section('Encabezado', 'Nuestro blog')
@section('content')
@section('Boton', 'Informate!')
@include('posts.blog')
@include('include.cta')
@include('include.footer')
@endsection
