@extends('master')
@section('titulo', 'Obras sociales | CKFM')
@section('Encabezado', 'obras sociales')
@section('cont', '')
@section('Boton', '')
@section('content')
    @include('obras.emp')
    @include('include.cta')
    @include('include.footer')
@endsection
